### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by Yeti-or** [bem/sssr#6]
@aristov 

bower bem-components#bemup-minsk-2014            error Arguments to path.join must be strings

ошбика на самом деле во время  ``bower install``

причем все ок если 
```
bower -v
1.3.12
```
и все плохо если 

```
5:sssr yeti-or$ bower -v
1.2.8
```

**Comment by dab** [comment]
@YetiOr посмотри ветку [cocaine](https://github.com/bem/sssr/tree/cocaine). Она должна быть актуальная.

**Comment by aristov** [comment]
@dab а в статье http://habrahabr.ru/company/yandex/blog/251473/ мы базируемся на ветке master? Если да, но должно работать.

**Comment by dab** [comment]
@aristov нет, для статьи я сделаю отдельную ветку и добавлю в комменты

**Comment by YetiOr** [comment]
ну тогда сделайте главной ветку ту в которой приходишь и все работает?

2015-03-02 18:57 GMT+03:00 Dima Belitsky <notifications@github.com>:

**Comment by dab** [comment]
@YetiOr так и сделаем

**Comment by raining** [comment]
Здравствуйте! Изучаю примеры, и в том числе решила изучить этот пример сначала по вышеозвученной статье, а потом уже посмотреть этот репозиторий.
Написать решила в эту ветку, так как сначала возник сабж, а потом уже то что ниже. (может это из-за разных версий в ветках)

Собрать удалось только действительно по ветке cocaine, и с помощью команд которые в readme.md описаны.
Вопрос вот в чем - после запуска этого проекта по нажатию кнопки "Автоскролл"  в консоль валится "undefined is not a function", и выведенный объект 

 autoscroll Object {__base: undefined, domElem: n.fn.init[1], _eventNameCache: Object, _elemCache: Object, _uniqId: "uniq5uniq1"…}

Программа вроде работает, но все равно неприятно. Почему такое происходит?

**Comment by dab** [comment]
@raining Посмотрите https://github.com/bem/sssr 
добавил актуальный код из статьи в ветку `habrahabr`.

**Comment by raining** [comment]
Упс, упало на команде последней
`
> node ./desktop.bundles/index/index.node.js 

module.js:340
    throw err;
          ^
Error: Cannot find module '../../desktop.blocks/service/_type/service_type_instagram.node.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.require.resolve (module.js:384:19)
    at Object.<anonymous> (/home/rw/projects/sssr/desktop.bundles/index/index.node.js:445:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
`

**Comment by raining** [comment]
я добавила файлы вручную у себя на другую ветку, но все равно по выборе instagram не ищет, и ошибка в консоли еще естьс автоскроллом. Все остальное работает :)
