### ISSUE TITLE
Нет файла index.node.js

### ISSUE THREAD

**Issue by mathetes** [bem/sssr#9]
Склонировал. Установил зависимости без ошибок.
Прошу сделать node ./desktop.bundles/index/index.node.js

А в ответ
module.js:338
    throw err;
    ^

Error: Cannot find module '/home/roman/allApps/01_BEM/sssr/desktop.bundles/index/index.node.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3

**Comment by tadatuta** [comment]
@mathetes В ридми был пропущен этап про сборку проекта (`./node_modules/enb/bin/enb make`), [добавил](https://github.com/bem/sssr/commit/3e8b0cd1b95eedb3bc94cf8563741d00209d9784).

Спасибо!
